version: '3.8'

services:
  db:
    image: postgres:16-alpine3.18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=invo-smart
    ports:
      - '5435:5432'
    volumes:
      - db:/var/lib/postgresql/data
  api:
    extends:
      file: docker-compose.base.yml
      service: app-base
    command: npm run api:serve
    depends_on:
     - db
    ports:
      - '3000:3000'
  api-e2e:
    environment:
      - HOST=api
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/invo-smart?schema=public
    extends:
      file: docker-compose.base.yml
      service: app-base
    command: npx nx run api-e2e:e2e
    depends_on:
      - api
  tests:
    extends:
      file: docker-compose.base.yml
      service: app-base
    command: npm run test
    depends_on:
      - db
volumes:
  mono-node-modules: null
  db:
    driver: local
